-- 코드를 입력하세요
SELECT DISTINCT M_CART_ID AS CART_ID FROM(
SELECT M.CART_ID AS M_CART_ID, Y.CART_ID AS Y_CART_ID FROM
(SELECT CART_ID FROM CART_PRODUCTS
WHERE NAME IN ('Milk')) M,
(SELECT CART_ID FROM CART_PRODUCTS
WHERE NAME IN ('Yogurt')) Y)
WHERE M_CART_ID = Y_CART_ID
ORDER BY M_CART_ID
