-- 코드를 입력하세요

SELECT TO_CHAR(N.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE,N.PRODUCT_ID,N.USER_ID,N.SALES_AMOUNT 
FROM ONLINE_SALE N
WHERE TO_CHAR(N.SALES_DATE, 'YYYY-MM') = '2022-03'

UNION ALL

SELECT TO_CHAR(F.SALES_DATE,'YYYY-MM-DD') AS SALES_DATE, F.PRODUCT_ID,NULL AS USER_ID, F.SALES_AMOUNT 
FROM OFFLINE_SALE F
WHERE TO_CHAR(F.SALES_DATE, 'YYYY-MM') = '2022-03'

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC