-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O ON (I.ANIMAL_ID = O.ANIMAL_ID)
WHERE SUBSTR(SEX_UPON_INTAKE,1,6) = 'Intact' 
AND (SEX_UPON_OUTCOME LIKE 'Spayed%' 
OR SEX_UPON_OUTCOME LIKE 'Neutered%' )

