-- 코드를 입력하세요
SELECT B.HOUR, DECODE(A.COUNT,NULL,0,A.COUNT) AS COUNT FROM
(SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR, COUNT(ANIMAL_ID) AS COUNT FROM ANIMAL_OUTS
GROUP BY TO_NUMBER(TO_CHAR(DATETIME,'HH24'))) A,
(SELECT LEVEL-1 AS HOUR FROM DUAL CONNECT BY LEVEL < 25) B
WHERE (A.HOUR(+) = B.HOUR)
ORDER BY B.HOUR
