-- 코드를 입력하세요
-- SELECT NAME, DATETIME 
-- FROM ANIMAL_INS
-- WHERE NAME NOT IN (
--     SELECT I.NAME AS NAME
--       FROM ANIMAL_INS I, ANIMAL_OUTS O
--         WHERE I.NAME = O.NAME ) 


SELECT NAME, DATETIME
FROM
(
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS A
LEFT JOIN
ANIMAL_OUTS B
ON A.ANIMAL_ID=B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY DATETIME
)
WHERE ROWNUM<=3

-- SELECT * FROM ANIMAL_INS
-- ORDER BY NAME