-- -- 코드를 입력하세요

SELECT P.PRODUCT_ID, P.PRODUCT_NAME,SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P 
INNER JOIN FOOD_ORDER O ON (P.PRODUCT_ID = O.PRODUCT_ID)
WHERE TO_CHAR(PRODUCE_DATE,'YYYYMM') LIKE '202205' 
GROUP BY P.PRODUCT_ID,P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC


-- SELECT P.PRODUCT_ID, P.PRODUCT_NAME,(P.PRICE*O.AMOUNT) AS TOTAL_SALES
-- FROM FOOD_PRODUCT P 
-- INNER JOIN FOOD_ORDER O ON (P.PRODUCT_ID = O.PRODUCT_ID)
-- WHERE TO_CHAR(PRODUCE_DATE,'YYYYMM') LIKE '202205'