-- 코드를 입력하세요

SELECT
DECODE(TO_CHAR(DATETIME, 'HH24'),09,9,TO_CHAR(DATETIME, 'HH24')) AS HOUR
, COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME, 'HH24') >= '09' AND TO_CHAR(DATETIME, 'HH24') <= '20'
ORDER BY HOUR