-- 코드를 입력하세요
-- SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
--     FROM (SELECT I.INGREDIENT_TYPE AS INGREDIENT_TYPE, F.TOTAL_ORDER AS TOTAL_ORDER
--         FROM FIRST_HALF F
--         INNER JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR)
--     GROUP BY INGREDIENT_TYPE
SELECT I.INGREDIENT_TYPE , SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO I, FIRST_HALF F
WHERE I.FLAVOR = F.FLAVOR
GROUP BY I.INGREDIENT_TYPE